name: php-8.3
version: "8.3.16"
description: PHP 8.3 NTS x64 for Windows
platform: win32
arch: x64
url: https://windows.php.net/downloads/releases/archives/php-8.3.16-nts-Win32-vs16-x64.zip
installPath: bin/php/php-8.3
binary: php.exe
postInstall:
  - copy: php.ini-development → php.ini
