name: php-8.3
version: "8.3.20"
description: PHP 8.3 FPM+CLI (static-php.dev common) for macOS arm64
platform: darwin
arch: arm64
url: https://dl.static-php.dev/static-php-cli/common/php-8.3.20-fpm-macos-aarch64.tar.gz
installPath: bin/php/php-8.3
binary: sbin/php-fpm
downloadType: tar.gz
