import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.join(__dirname, "..", "..", "..");
const distUi = path.join(__dirname, "..", "dist", "ui");

fs.mkdirSync(distUi, { recursive: true });

// UI assets
fs.cpSync(path.join(__dirname, "..", "src", "ui"), distUi, { recursive: true });

// Transparent UI mark for dashboard / tray popup (generated by npm run generate-icons)
const assetsDir = path.join(__dirname, "..", "assets");
const appIcon = path.join(assetsDir, "icon-ui.png");
const appIconFallback = path.join(assetsDir, "icon-128.png");
const appIconSrc = fs.existsSync(appIcon) ? appIcon : appIconFallback;
if (fs.existsSync(appIconSrc)) {
  fs.copyFileSync(appIconSrc, path.join(distUi, "app-icon.png"));
}

// Bundled manifests & templates for Quick Add / Quick App in the desktop app
const distManifests = path.join(__dirname, "..", "dist", "manifests");
const distTemplates = path.join(__dirname, "..", "dist", "templates");
const srcManifests = path.join(repoRoot, "manifests");
const srcTemplates = path.join(repoRoot, "templates");

if (fs.existsSync(srcManifests)) {
  fs.cpSync(srcManifests, distManifests, { recursive: true });
}
if (fs.existsSync(srcTemplates)) {
  fs.cpSync(srcTemplates, distTemplates, { recursive: true });
}

console.log("Copied UI, manifests, and templates to dist/");
